# Практическая работа № 5 «Тайные многосторонние вычисления и разделение секрета»
 
В практической работе необходимо привести последовательность выполнения следующих протоколов:
- тайных многосторонних вычислений для расчета средней величины трех чисел. В качестве исходных данных принять коды 1-ой, 2-ой и 3-ей буквы своей фамилии согласно их положению в алфавите;
- разбиения секрета с использование гаммирования для трех участников. В качестве секрета принять первые 3 буквы фамилии, для гамм - любые трехбуквенные сочетания;
- разделения секрета по схеме Шамира для (3, 5)-пороговой схемы. В качестве секрета S принять код 1-ой буквы своей фамилии согласно ее положению в алфавите;
- разделения секрета по схеме Асмута-Блума для (3, 5)-пороговой схемы. В качестве секрета S принять код 1-ой буквы своей фамилии согласно ее положению в алфавите.

При оформлении отчета необходимо привести исходные данные и таблицы, содержащие последовательность выполнения протоколов. Отчет необходимо загрузить в edu.susu.ru


In [1]:
import json


import numpy as np
import pandas as pd

from scipy.interpolate import lagrange
from numpy.polynomial.polynomial import Polynomial

In [2]:
with open('instance/settings.json') as f:
    settings = json.load(f)
    LAST_NAME = settings['last_name']
    FIRST_NAME = settings['first_name']
    PATRONYMIC = settings['patronymic']

In [3]:
def gcd_ext(a, b):
    """
    Find a*x+b*y = gcd(a, b)
    """
    if a == 0:
        return b, 0, 1
    d, x, y = gcd_ext(b % a, a)
    return d, y - (b // a) * x, x

In [4]:
def rev_element_by_modulo(num, mod):
    g, x, y = gcd_ext(num, mod)
    if g != 1:
        return None
    return (x % mod + mod) % mod

In [5]:
def power_with_modulo(a, n, m):
    res = 1
    while n > 0:
        if (n & 1) == 1:
            res = (res * a) % m
        a = (a * a) % m
        n >>= 1
    return res

## Тайные многосторонние вычисления

In [6]:
def rsa_generator():
    keys = [
        [5, 91, 29],
        [7, 91, 31],
        [17, 91, 17],
    ]
    for e, n, d in keys:
        yield {'public': {'e': e, 'n': n}, 'private': {'d': d}}

In [7]:
smc_data = list(map(lambda c: ord(c) - ord('a') + 1, LAST_NAME[:3]))
smc_data = {k: {'secret': v, 'rsa': rsa} for k, v, rsa in zip('abc', smc_data, rsa_generator())}
print(json.dumps(smc_data, indent=4))

{
    "a": {
        "secret": 1,
        "rsa": {
            "public": {
                "e": 5,
                "n": 91
            },
            "private": {
                "d": 29
            }
        }
    },
    "b": {
        "secret": 12,
        "rsa": {
            "public": {
                "e": 7,
                "n": 91
            },
            "private": {
                "d": 31
            }
        }
    },
    "c": {
        "secret": 11,
        "rsa": {
            "public": {
                "e": 17,
                "n": 91
            },
            "private": {
                "d": 17
            }
        }
    }
}


<b>A</b> прибавляет случайное секретное число $x$ к своему секрету, шифрует результат с помощью открытого ключа <b>B</b> и отсылает его <b>B</b>

In [8]:
np.random.seed(42)
a_x = np.random.randint(2, 1<<20)

a_data = smc_data['a']['secret'] + a_x
shared_data = power_with_modulo(
    a_data, 
    smc_data['b']['rsa']['public']['e'], 
    smc_data['b']['rsa']['public']['n'],
)

{{f'$secret_a = {smc_data["a"]["secret"]}$'}}  
{{f'$x_a = {a_x}$'}}  
{{f'$data_a = {a_data}$'}}   
{{f'$shared\\_data = {shared_data}$'}}

<b>B</b> расшифровывает результат, добавляет к нему свою зарплату, шифрует результат с помощью открытого ключа <b>C</b> и отсылает его <b>C</b>.

In [9]:
decrypted_data = power_with_modulo(
    shared_data, 
    smc_data['b']['rsa']['private']['d'], 
    smc_data['b']['rsa']['public']['n'],
)
b_data = decrypted_data + smc_data['b']['secret']
shared_data = power_with_modulo(
    b_data, 
    smc_data['c']['rsa']['public']['e'], 
    smc_data['c']['rsa']['public']['n'],
)

{{f'$secret_b = {smc_data["b"]["secret"]}$'}}  
{{'$data_{decrypted} = %d$' % decrypted_data}}  
{{f'$data_b = {b_data}$'}}   
{{f'$shared\\_data = {shared_data}$'}}

In [10]:
decrypted_data = power_with_modulo(
    shared_data, 
    smc_data['c']['rsa']['private']['d'], 
    smc_data['c']['rsa']['public']['n'],
)
c_data = decrypted_data + smc_data['c']['secret']
shared_data = power_with_modulo(
    c_data, 
    smc_data['a']['rsa']['public']['e'], 
    smc_data['a']['rsa']['public']['n'],
)

{{f'$secret_c = {smc_data["c"]["secret"]}$'}}  
{{'$data_{decrypted} = %d$' % decrypted_data}}  
{{f'$data_c = {c_data}$'}}   
{{f'$shared\\_data = {shared_data}$'}}

In [11]:
decrypted_data = power_with_modulo(
    shared_data, 
    smc_data['a']['rsa']['private']['d'], 
    smc_data['a']['rsa']['public']['n'],
)
final_data = (decrypted_data - a_x) % smc_data['a']['rsa']['public']['n']

{{'$data_{decrypted} = %d$' % decrypted_data}}   
{{'$data_{final} = %d$' % final_data}}  
{{f'$secret_a + secret_b + secret_c = {smc_data["a"]["secret"] + smc_data["b"]["secret"] +smc_data["c"]["secret"]}$'}}   

## Разбиение секрета с использование гаммирования

In [12]:
ssg_data = LAST_NAME[:3]
print(ssg_data)

alk


Кодирование секрета

In [13]:
def get_binary(word):
    return list(map(lambda c: '{0:0>8b}'.format(c), word.encode('cp1251')))

In [14]:
pd.DataFrame({
    'Символ': list(ssg_data),
    'Бинарный код': get_binary(ssg_data)
}).set_index('Символ').T

Символ               a         l         k
Бинарный код  01100001  01101100  01101011

In [15]:
def get_gamma(size, seed):
    random = np.random.RandomState(seed)
    res = ''
    for i in range(size):
        res += chr(ord('a') + random.randint(0, 26))
    return res

In [16]:
def get_gammas(n, size):
    names = [f'Гамма{i + 1}' for i in range(n)]
    values = [get_gamma(size, i) for i in range(n)]
    bin_values = [get_binary(v) for v in values]
    values = list(map(list , values))
    values_title =  [f'{g} Символ {i + 1}' for i, g in enumerate(names)]
    res = {}
    for i, name in enumerate(names):
        res[f'{name} Символ'] = values[i]
        res[f'{name} Бинарный код'] = bin_values[i]
    return res

Генерация случайных гамм и передача их участникам.

In [17]:
ssg_df = pd.DataFrame({
    'Символ': list(ssg_data),
    'Бинарный код': get_binary(ssg_data),
    **get_gammas(3, len(ssg_data))
}).set_index('Символ').T
ssg_df

Символ                      a         l         k
Бинарный код         01100001  01101100  01101011
Гамма1 Символ               m         p         v
Гамма1 Бинарный код  01101101  01110000  01110110
Гамма2 Символ               f         l         m
Гамма2 Бинарный код  01100110  01101100  01101101
Гамма3 Символ               i         p         n
Гамма3 Бинарный код  01101001  01110000  01101110

Получение шифрограммы и выкладывание её в доступное для участников место.

In [18]:
def get_cipher(data):
    res = []
    for row in data:
        n = len(row[0])
        cur = np.zeros((n,), dtype=int)
        for i in range(n):
            for v in row:
                cur[i] = (cur[i] + int(v[i])) % 2
        res.append(''.join(map(str, cur)))   
    return np.array(res)

In [19]:
cipher = get_cipher(ssg_df.values[::2].T)
cipher

array(['00000011', '00000000', '00011110'], dtype='<U8')

In [20]:
ssgc_df = ssg_df.T.assign(Шифрограммы=cipher).T
ssgc_df

Символ                      a         l         k
Бинарный код         01100001  01101100  01101011
Гамма1 Символ               m         p         v
Гамма1 Бинарный код  01101101  01110000  01110110
Гамма2 Символ               f         l         m
Гамма2 Бинарный код  01100110  01101100  01101101
Гамма3 Символ               i         p         n
Гамма3 Бинарный код  01101001  01110000  01101110
Шифрограммы          00000011  00000000  00011110

Восстановление кода

In [21]:
gammas = ssg_df.values[2::2]
gammas

array([['01101101', '01110000', '01110110'],
       ['01100110', '01101100', '01101101'],
       ['01101001', '01110000', '01101110']], dtype=object)

In [22]:
cipher

array(['00000011', '00000000', '00011110'], dtype='<U8')

In [23]:
bin_decodes = get_cipher(np.vstack((gammas, cipher)).T)
bin_decodes

array(['01100001', '01101100', '01101011'], dtype='<U8')

In [24]:
decodes = list(map(lambda x: int(x, 2), get_cipher(np.vstack((gammas, cipher)).T)))
decodes

[97, 108, 107]

In [25]:
bytes(decodes).decode('cp1251')

'alk'

### Разделение секрета по схеме Шамира (интерполяционных полиномов Лагранжа)

In [26]:
secret = ord(LAST_NAME[0]) - ord('a') + 1
secret

1

Количество долей, необходимых для восстановления секрета

In [27]:
m = 3

Общее количество долей

In [28]:
n = 5

#### Процедура определения и распределения долей
Выполняет владелец

Выбор простого числа $p$, которое больше количества долей $n$ и секрета $S$.

In [29]:
p = 59

Выбор произвольного многочлена степени $m-1 : f(x) = (а_2*х_2 + a_1*x + S) \bmod p$, где значения $а_2$ и $a_1$ выбираются случайным образом, хранятся в тайне и отбрасываются после распределения долей.

In [30]:
a = [10, 23, secret]
f = lambda x: sum(c*v**(len(x) - i) for i, (c, v) in enumerate(zip(a, list(x) + [1]))) % p

Определение долей $(x_i, y_i)$, где $y_i = f(x_i)$ и $x_i = i + 1$.

In [31]:
x = np.arange(1, n + 1)
x

array([1, 2, 3, 4, 5])

In [32]:
y = list(map(f, [(v, v) for v in x]))
y

[34, 28, 42, 17, 12]

Публикация $p$ и распределение долей $(x_i, y_i)$ между участниками.

In [33]:
xy = np.array([x, y]).T
xy, p

(array([[ 1, 34],
        [ 2, 28],
        [ 3, 42],
        [ 4, 17],
        [ 5, 12]]), 59)

#### Процедура восстановления секрета
Выполняют участники

Сбор $m$ долей

In [34]:
parts = xy[[1, 2, 4]]
parts

array([[ 2, 28],
       [ 3, 42],
       [ 5, 12]])

Получение полинома Лагранжа

In [35]:
l = lagrange(parts[:, 0], parts[:, 1])

Вычисление $s^\prime$

In [36]:
s_prime = int(Polynomial(np.mod(lagrange(parts[:, 0], parts[:, 1]), 59)).coef[2]) % p
s_prime

1

### Разделение секрета по схеме Асмута-Блума

In [37]:
secret = ord(LAST_NAME[0]) - ord('a') + 1
secret

1

Количество долей, необходимых для восстановления секрета

In [38]:
m = 3

Общее количество долей

In [39]:
n = 5

#### Процедура определения и распределения долей
Выполняет владелец

In [40]:
p = 13

Выбор $n$ взаимно простых чисел $d_i$, удовлетворяющих условиям:
- $d_i > p$
- $d_i < d_i+1$
- $d_1 * d_2 * … * d_m < p * d_{n-m+2} * d_{n-m+3} * … * d_n$

In [41]:
d = [17, 20, 23, 29, 37]
d

[17, 20, 23, 29, 37]

Выбор произвольного числа $r$, удовлетворяющего условию
$$
r < \frac{\prod_{i=1}^m{d_i}-S}{p}
$$

In [42]:
r = 30

Вычисление $S^\prime = S + r*p$.

In [43]:
secret_prime = secret + r * p
secret_prime

391

Определение долей $(d_i, k_i)$, где $k_i = S^\prime \bmod d_i$.

In [44]:
k = list(map(lambda d_i: secret_prime % d_i, d))
k

[0, 11, 0, 14, 21]

In [45]:
dk = np.array([d, k]).T
dk

array([[17,  0],
       [20, 11],
       [23,  0],
       [29, 14],
       [37, 21]])

Публикация $p$ и распределение долей $(d_i, k_i)$ между участниками.

In [46]:
dk, p

(array([[17,  0],
        [20, 11],
        [23,  0],
        [29, 14],
        [37, 21]]), 13)

#### Процедура восстановления секрета
Выполняют участники

Сбор $m$ долей.

In [47]:
parts = dk[[1, 2, 4]]
parts

array([[20, 11],
       [23,  0],
       [37, 21]])

Вычисление произведения $D$ взаимно простых чисел $d_j$.

In [48]:
prod_d = np.prod(parts[:, 0])
prod_d

17020

Вычисление сомножителей $D_j = D / d_j$.

In [49]:
prods = np.array([prod_d] * 3, dtype=int) // parts[:, 0]
prods

array([851, 740, 460])

Определение обратных чисел $D_j^{-1}$ по модулям $d_j$.

In [50]:
inv_prods = list(map(lambda e: rev_element_by_modulo(*e), zip(prods, parts[:, 0])))
inv_prods

[11, 6, 7]

Вычисление $S^\prime = (\sum{k_j*D_j*D_j^{-1}}) \bmod D$.

In [51]:
secret_prime = sum(map(np.prod, zip(parts[:, 1], prods, inv_prods))) % prod_d
secret_prime

391

Определение секрета $S = S^\prime \bmod p$

In [52]:
secret_c = secret_prime % p
secret_c

1